-- The shop's loyalty rates, details, announcements and membership benefits move from code
-- into the database.
--
-- Paste this over the body of the migration generated by:
--   npx prisma migrate dev --create-only --name shop_settings_from_code
-- run from C:\Personal Projects\eversweet
--
-- Prisma's own generated SQL would create the three tables, add MembershipPlan.benefits as
-- an empty column, and stop there. That leaves every reader falling back to its own
-- hard-coded copy, which is the thing this migration exists to end: the earn rate was
-- written out three times and the three disagreed (the order server 6, the customer app's
-- fallback 5, a dead helper in the staff app a third figure), and the shop's address four
-- times in two different formats. So this seeds each table with exactly the values the code
-- holds today, adds the CHECK constraints Prisma cannot express, and backfills the benefits
-- before asserting they arrived.
--
-- The seeded values reproduce current behaviour precisely, with one exception, called out
-- because it is a change and not a copy: the benefits list advertised "Earn 2x loyalty
-- points" while the rate gave members 1.5x. It is seeded as "{{memberRate}}x" instead, a
-- token the order server fills in from LoyaltySetting when it serves the benefits, so the
-- sentence cannot disagree with the rate again. Nothing about what anyone earns changes -
-- LoyaltySetting is seeded with the rates as they stand.
--
-- The announcements are seeded as they are, placeholder text and all, because a migration
-- is the wrong place to decide what the shop wants to say. Their publishedAt keeps the
-- dates the constants carried, so a customer who has already dismissed one is not shown it
-- again: the app compares publishedAt against the last announcement it displayed.
--
-- Purely additive. Nothing reads any of this until the order server and website deploy, so
-- it runs before both, and there is no pre-existing state to assert against beyond the
-- backfill in step 8.

-- 1. Loyalty rates, exactly as Prisma would create the table. Whole numbers only: the
--    Decimal fraction on Offer.discountAmount was read as `1 - x` and priced a 20% offer at
--    -19x list, and the fix there was to store whole percent. The order server divides by
--    100 at the edge so the wire shape installed builds parse is unchanged.
CREATE TABLE "LoyaltySetting" (
    "id" TEXT NOT NULL,
    "pointsPerDollar" INTEGER NOT NULL DEFAULT 6,
    "memberBonusPercent" INTEGER NOT NULL DEFAULT 150,
    "modifierPercent" INTEGER NOT NULL DEFAULT 100,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "LoyaltySetting_pkey" PRIMARY KEY ("id")
);

-- 2. Points cannot be negative, and a member must never earn less than a non-member - a
--    member bonus below 100 would quietly punish the people paying for the membership.
ALTER TABLE "LoyaltySetting" ADD CONSTRAINT "LoyaltySetting_points_not_negative"
  CHECK ("pointsPerDollar" >= 0);

ALTER TABLE "LoyaltySetting" ADD CONSTRAINT "LoyaltySetting_member_never_worse"
  CHECK ("memberBonusPercent" >= 100);

ALTER TABLE "LoyaltySetting" ADD CONSTRAINT "LoyaltySetting_modifier_not_negative"
  CHECK ("modifierPercent" >= 0);

-- 3. The shop's details. isOpen is deliberately not a column: it is worked out per request
--    from TradingHours and DaysOff, having once been computed at server start and then
--    served unchanged until the next deploy.
CREATE TABLE "ShopProfile" (
    "id" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "address" TEXT NOT NULL,
    "city" TEXT NOT NULL,
    "state" TEXT NOT NULL,
    "postal" TEXT NOT NULL,
    "phone" TEXT NOT NULL,
    "email" TEXT NOT NULL,
    "website" TEXT NOT NULL,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "ShopProfile_pkey" PRIMARY KEY ("id")
);

-- 4. The launch pop-up's messages.
CREATE TABLE "Announcement" (
    "id" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "text1" TEXT NOT NULL,
    "text2" TEXT,
    "publishedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "isActive" BOOLEAN NOT NULL DEFAULT true,
    "position" INTEGER NOT NULL DEFAULT 0,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "Announcement_pkey" PRIMARY KEY ("id")
);

-- 5. Seed the two singletons with the literal id the PrepTimeSetting migration used, so the
--    settings screen has something to edit and neither service is relying on its fallback
--    from the moment it deploys. The column defaults are the rates that were hard-coded, so
--    this changes nothing about what an order earns.
INSERT INTO "LoyaltySetting" ("id", "updatedAt")
VALUES ('default', NOW())
ON CONFLICT ("id") DO NOTHING;

INSERT INTO "ShopProfile" (
  "id", "name", "address", "city", "state", "postal", "phone", "email", "website", "updatedAt"
) VALUES (
  'default',
  'Eversweet',
  '5D/119 Meadowland Drive, Somerville',
  'Auckland',
  'Auckland',
  '2014',
  '09 949 1050',
  'eversweet@eversweet.co.nz',
  'https://eversweet.co.nz',
  NOW()
)
ON CONFLICT ("id") DO NOTHING;

-- 6. The announcements as the constant holds them, in its array order, keeping the dates it
--    carried so nothing a customer has already dismissed reappears.
INSERT INTO "Announcement" (
  "id", "title", "text1", "text2", "publishedAt", "position", "createdAt", "updatedAt"
) VALUES
  (
    'announcement_seed_1',
    'Announcement',
    'This is an announcement message. ',
    'We are just testing this announcement...',
    TIMESTAMP '2026-06-18 00:00:00',
    0,
    NOW(),
    NOW()
  ),
  (
    'announcement_seed_2',
    'Promotion',
    'We have a promotion going on, check the home page for more details.',
    NULL,
    TIMESTAMP '2025-06-18 00:00:00',
    1,
    NOW(),
    NOW()
  )
ON CONFLICT ("id") DO NOTHING;

-- 7. Membership benefits. Added exactly as Prisma declares a scalar list - no NOT NULL and
--    no DEFAULT - so that a later `migrate diff` reports empty rather than proposing to
--    rebuild the column.
ALTER TABLE "MembershipPlan" ADD COLUMN "benefits" TEXT[];

UPDATE "MembershipPlan"
SET    "benefits" = ARRAY[
         'Free weekly Mochi Series Bowl ($9.99)',
         'Stackable membership discount from 5% to 25%, up by 5% each month',
         'Earn {{memberRate}}x loyalty points',
         'Exclusive membership offers',
         'Cancel anytime'
       ]
WHERE  "benefits" IS NULL OR cardinality("benefits") = 0;

-- 8. Load-bearing assertion. A plan with no benefits renders as an empty list on the join
--    screen - a membership that appears to offer nothing - and the failure would be silent.
--    Guarded on the table being non-empty, because `prisma migrate dev` replays every
--    migration into an empty shadow database and an unguarded count would fail there
--    forever, for everyone (see 20260913000000_offer_renews_weekly).
DO $$
DECLARE
  plans   INTEGER;
  without INTEGER;
BEGIN
  SELECT COUNT(*) INTO plans FROM "MembershipPlan";

  IF plans > 0 THEN
    SELECT COUNT(*) INTO without
    FROM   "MembershipPlan"
    WHERE  "benefits" IS NULL OR cardinality("benefits") = 0;

    IF without <> 0 THEN
      RAISE EXCEPTION 'membership benefits: % plan(s) left with no benefits', without;
    END IF;
  END IF;
END $$;

-- 9. Assert the singletons landed. Each is created above, so this holds on the empty shadow
--    database too. A missing row is not fatal at runtime - both readers fall back to the
--    constants they used to hold - but it would mean the admin screen has nothing to edit
--    and the fallback is load-bearing in production, which is not the arrangement intended.
DO $$
DECLARE
  rates   INTEGER;
  profile INTEGER;
BEGIN
  SELECT COUNT(*) INTO rates   FROM "LoyaltySetting";
  SELECT COUNT(*) INTO profile FROM "ShopProfile";

  IF rates <> 1 OR profile <> 1 THEN
    RAISE EXCEPTION
      'shop settings: expected one LoyaltySetting and one ShopProfile, found % and %',
      rates, profile;
  END IF;
END $$;
