-- Offer schedule window, soft delete, percent discounts; drop dead renewsAt
--
-- Paste this over the body of the migration generated by:
--   npx prisma migrate dev --create-only --name offer_window_and_discount_percent
-- run from C:\Personal Projects\eversweet
--
-- Prisma wraps each migration in a transaction, so a failure at step 2 leaves the
-- database exactly as it was.
--
-- IMPORTANT: prisma/schema.prisma is byte-identical with the order server's copy, and
-- so is this file. Copy the whole folder across unchanged - Prisma checksums
-- migration.sql, and a reformatted copy fails `migrate deploy` there with a checksum
-- mismatch rather than a merge conflict. Apply from one repo only; both point at the
-- same database.

-- 1. The three new columns. Nullable with no default, so PostgreSQL records them in the
--    catalogue and rewrites no rows, and every Offer that exists today reads back as
--    "no start bound, no end bound, not archived" - exactly the behaviour it has now,
--    where isActive is the only gate. NULL is load-bearing rather than a placeholder:
--      startsAt   NULL -> runs as soon as isActive is set
--      endsAt     NULL -> runs until switched off
--      archivedAt NULL -> not archived
--    so having no backfill here is correct, not merely convenient.
ALTER TABLE "Offer" ADD COLUMN "startsAt" TIMESTAMP(3);

ALTER TABLE "Offer" ADD COLUMN "endsAt" TIMESTAMP(3);

ALTER TABLE "Offer" ADD COLUMN "archivedAt" TIMESTAMP(3);

-- 2. Load-bearing assertion in front of the type change. discountAmount currently holds
--    a FRACTION: cart.controller.ts prices at `1 - discountAmount`, and offerCard.tsx
--    renders `discountAmount * 100` followed by "% off", so 20% off is stored as 0.2.
--    A plain ::INTEGER cast would round 0.2 down to 0 and silently charge full price on
--    every percentage-based offer. Anything outside 0..1, or that does not land on a
--    whole percent, means that reading is wrong - so this fails and rolls back rather
--    than guessing at what the value meant.
DO $$
DECLARE bad INTEGER;
BEGIN
  SELECT COUNT(*) INTO bad FROM "Offer"
  WHERE "discountAmount" IS NOT NULL
    AND ("discountAmount" < 0
      OR "discountAmount" > 1
      OR "discountAmount" * 100 <> ROUND("discountAmount" * 100));
  IF bad > 0 THEN
    RAISE EXCEPTION
      'discountAmount: % row(s) are not a whole percent within 0..1; convert by hand', bad;
  END IF;
END $$;

-- 3. Fraction -> whole percent. The * 100 is the whole point of this statement.
ALTER TABLE "Offer"
  ALTER COLUMN "discountAmount" TYPE INTEGER
  USING ROUND("discountAmount" * 100)::INTEGER;

-- 4. renewsAt is dead. renewMochiOffer - the weekly job the OfferRedemption doc comment
--    names - is in full `offerRedemption.updateMany({ data: { used: 0 } })`: no WHERE
--    clause, and no reference to this column. A grep across the order server and both
--    Expo apps finds one hit, a type declaration in frontend/utils/types.ts, which
--    nothing reads. No SQL assertion can prove "nothing reads this", so the evidence is
--    that scan, recorded here.
ALTER TABLE "OfferRedemption" DROP COLUMN "renewsAt";
