-- Split the membership's month count in two: the consecutive run, and every month ever paid.
--
-- Paste this over the body of the migration generated by:
--   npx prisma migrate dev --create-only --name membership_lifetime_months
-- run from C:\Personal Projects\eversweet
--
-- Prisma's own generated SQL would be the ALTER TABLE in step 1 alone, which would start
-- every existing member at 0. That is wrong in a way that matters: the order server now reads
-- `lifetimeMonths > 0` as "this membership was paid for", which is what anchors a lapsed
-- member's points expiry on the day their membership ended. At 0, every member who has ever
-- left would lose that anchor on deploy and could have their points expire the next night.
--
-- So step 2 seeds it from `totalMonths`, the run, which is a lower bound: every month in the
-- run was paid. Months paid before a break are not in the run and cannot be known here; the
-- order server's `src/scripts/backfillLifetimeMonths.ts` reads them from Stripe after deploy.
--
-- `totalMonths` keeps its meaning and its name - installed app builds read it off the wire as
-- the run - but the order server now zeroes it when a subscription ends, which is only safe
-- once this column carries "was ever paid". Run this before deploying that server.

-- 1. The column, exactly as Prisma would add it.
ALTER TABLE "Membership" ADD COLUMN "lifetimeMonths" INTEGER NOT NULL DEFAULT 0;

-- 2. Seed it from the run.
UPDATE "Membership" SET "lifetimeMonths" = "totalMonths";

-- 3. Load-bearing. Every paid month in the run is a paid month, so no row may count fewer in
--    its lifetime than in its run; a row that did would read as never paid while it had
--    months in hand. Holds trivially on the empty shadow database.
DO $$
DECLARE
  wrong INTEGER;
BEGIN
  SELECT COUNT(*) INTO wrong
  FROM   "Membership"
  WHERE  "lifetimeMonths" < "totalMonths";

  IF wrong <> 0 THEN
    RAISE EXCEPTION
      'membership lifetime months: % membership(s) count fewer months in their lifetime than in their run',
      wrong;
  END IF;
END $$;
