-- Mark which offer renews every week
--
-- Paste this over the body of the migration generated by:
--   npx prisma migrate dev --create-only --name offer_renews_weekly
-- run from C:\Personal Projects\eversweet
--
-- Prisma wraps each migration in a transaction, so a failure at step 3 leaves the
-- database exactly as it was.
--
-- IMPORTANT: prisma/schema.prisma is byte-identical with the order server's copy, and so
-- is this file. Copy the whole folder across unchanged - Prisma checksums migration.sql,
-- and a reformatted copy fails `migrate deploy` there with a checksum mismatch. Apply
-- from one repo only; both point at the same database.
--
-- Why this column exists. The order server's weekly cron is in full:
--
--   offerRedemption.updateMany({ data: { used: 0 } })
--
-- no WHERE clause at all - so every Monday it zeroed the usage counter on every
-- OfferRedemption row in the database, not just the weekly mochi perk it is named after.
-- That was survivable only because `status` was written REDEEMED on every use and the
-- gate keyed off `status`, not `used`. Now that REDEEMED means "used up to the limit",
-- an unscoped reset would hand back every requirement-gated offer once a week - exactly
-- what closeRun deletes redemption rows to avoid. The cron needs to be told which offer
-- is the weekly one, and the offer row is the only place that fact belongs.
--
-- This replaces OfferRedemption.renewsAt, dropped in
-- 20260912000000_offer_window_and_discount_percent as dead: per-row renewal dates that
-- nothing ever read. Per-offer is the level the question is actually asked at.

-- 1. The column. NOT NULL DEFAULT false, so every existing offer reads as "does not
--    renew" - which, once the cron is scoped, is the behaviour they should have had all
--    along.
ALTER TABLE "Offer" ADD COLUMN "renewsWeekly" BOOLEAN NOT NULL DEFAULT false;

-- 2. Backfill. Load-bearing rather than cosmetic: the cron stops resetting anything the
--    moment it is scoped, so without this the membership's weekly mochi perk silently
--    stops renewing on the first Monday after the deploy, and nobody finds out until a
--    member complains.
UPDATE "Offer" SET "renewsWeekly" = true
WHERE "name" = 'Free weekly mochi dessert bowl';

-- 3. Assert the backfill actually matched. A rename of that offer would leave zero rows
--    flagged and silently retire the perk. Fail and roll back rather than deploy a dead
--    cron.
--
--    Guarded on the table being non-empty, and that guard is not defensive padding - it
--    is what lets `prisma migrate dev` work at all. That command validates by building a
--    throwaway shadow database and replaying every migration into it from nothing, so
--    "Offer" is empty when this runs there, the backfill matches no rows, and an
--    unguarded assertion fails with P3006 every single time. The check still bites on any
--    database that actually holds offers, which is the case it exists for.
--
--    A genuinely fresh production database would also skip it, correctly: there is no
--    perk to protect until someone seeds one, and whoever seeds it sets the flag.
DO $$
DECLARE
  total INTEGER;
  flagged INTEGER;
BEGIN
  SELECT COUNT(*) INTO total FROM "Offer";
  SELECT COUNT(*) INTO flagged FROM "Offer" WHERE "renewsWeekly";

  IF total > 0 AND flagged <> 1 THEN
    RAISE EXCEPTION
      'renewsWeekly: expected exactly 1 weekly offer after backfill, found % across % offer(s). The offer named ''Free weekly mochi dessert bowl'' is how this migration finds it - if it has been renamed, set the flag by hand instead.', flagged, total;
  END IF;
END $$;
