-- Records which Terms and Privacy Policy a customer accepted when they signed up.
--
-- Paste this over the body of the migration generated by:
--   npx prisma migrate dev --create-only --name record_legal_acceptance
-- run from C:\Personal Projects\eversweet
--
-- Prisma's own generated SQL is exactly the ALTER TABLE below, and that is all this needs.
-- It is written out rather than generated only so the reasoning for what it does *not* do
-- has somewhere to live.
--
-- The app's sign-up screen asks the customer to accept both documents, but nothing recorded
-- it: the checkbox was screen state, the request omitted it, and the endpoint had nowhere to
-- put it. So there was no answer to "did this customer agree, and to which version".
--
-- **Deliberately not backfilled.** Stamping existing accounts with the current version would
-- record an acceptance that never took place, which is worse than no record at all - it
-- would be a false answer to the only question these columns exist to answer. NULL is the
-- honest value for an account created before the screen asked, and
-- `WHERE "acceptedLegalAt" IS NULL` is how the shop finds them.
--
-- Nullable rather than NOT NULL for the same reason, and one more: a build already installed
-- does not send an acceptance, and requiring one would stop it signing up altogether. Once
-- every build sends it, `signUp` starts refusing and these can tighten.
--
-- Purely additive. Nothing reads the columns until the order server deploys, so it runs
-- before it, and there is no pre-existing state to assert against.

ALTER TABLE "User" ADD COLUMN "acceptedLegalVersion" TEXT;
ALTER TABLE "User" ADD COLUMN "acceptedLegalAt" TIMESTAMP(3);
