-- Sweet Points expire after a month without an app order.
--
-- Paste this over the body of the migration generated by:
--   npx prisma migrate dev --create-only --name points_expiry
-- run from C:\Personal Projects\eversweet
--
-- Prisma's own generated SQL would be the two ALTER TABLEs in step 1 and nothing else, and
-- for the columns that is exactly right: both are nullable, and NULL is the correct starting
-- value for each. `pointsExpireFrom` NULL means expiry is switched off, so deploying this
-- expires nobody - an admin switches it on from /admin/settings once the app build that
-- shows the deadline is live. `expiryWarnedFor` NULL means no warning has been sent.
--
-- What is hand-written is step 2, a data change Prisma knows nothing about: the membership
-- benefit that goes with the rule. It carries the {{whilePointsExpire}} token, which the
-- order server resolves by dropping the whole line while expiry is off. Without that the
-- list would advertise "points never expire while you're a member" at a time when nobody's
-- points expire at all - an advantage members do not actually have, which is the same
-- mistake as the "2x loyalty points" line 20260919000000 corrected.

-- 1. The columns, exactly as Prisma would add them.
ALTER TABLE "Loyalty" ADD COLUMN "expiryWarnedFor" TIMESTAMP(3);
ALTER TABLE "LoyaltySetting" ADD COLUMN "pointsExpireFrom" TIMESTAMP(3);

-- 2. The benefit, appended to every plan that does not already list it. Appended rather
--    than inserted, so the lines an admin has already ordered keep their order; and guarded,
--    so replaying this cannot list it twice.
UPDATE "MembershipPlan"
SET    "benefits" = array_append(
         COALESCE("benefits", ARRAY[]::TEXT[]),
         '{{whilePointsExpire}}Your Sweet Points never expire while you''re a member'
       )
WHERE  NOT ('{{whilePointsExpire}}Your Sweet Points never expire while you''re a member'
            = ANY(COALESCE("benefits", ARRAY[]::TEXT[])));

-- 3. Load-bearing. Every plan lists the benefit exactly once: missing, members are never
--    told; twice, the join screen says it twice. Guarded on the table being non-empty so it
--    holds on the empty shadow database `prisma migrate dev` replays into (see
--    20260913000000_offer_renews_weekly).
DO $$
DECLARE
  plans INTEGER;
  wrong INTEGER;
BEGIN
  SELECT COUNT(*) INTO plans FROM "MembershipPlan";

  IF plans > 0 THEN
    SELECT COUNT(*) INTO wrong
    FROM   "MembershipPlan" p
    WHERE  (SELECT COUNT(*)
            FROM   unnest(p."benefits") AS b
            WHERE  b = '{{whilePointsExpire}}Your Sweet Points never expire while you''re a member'
           ) <> 1;

    IF wrong <> 0 THEN
      RAISE EXCEPTION
        'points expiry: % membership plan(s) do not list the no-expiry benefit exactly once',
        wrong;
    END IF;
  END IF;
END $$;
