-- Records that customers have been told an offer exists.
--
-- Paste this over the body of the migration generated by:
--   npx prisma migrate dev --create-only --name offer_announcement
-- run from C:\Personal Projects\eversweet
--
-- Prisma's own generated SQL would be the ALTER TABLE in step 1 and nothing else. Left at
-- that, every offer already in the database would have a NULL `notifiedAt`, and the order
-- server's first sweep after deploying would read all of them as never announced and push
-- a notification for each, to every customer at once. The backfill in step 2 is the whole
-- reason this file is hand-written.
--
-- The column exists because there is no moment to hang a notification on otherwise: an
-- offer saved with a future `startsAt` becomes live at that instant with nothing written,
-- and `createOffer` and `updateOffer` can both set `isActive` without `setActive` being
-- called. The order server sweeps for live offers with this unset instead.

-- 1. The column, exactly as Prisma would add it.
ALTER TABLE "Offer" ADD COLUMN "notifiedAt" TIMESTAMP(3);

-- 2. Every offer that exists now counts as already announced. Customers have seen these -
--    they have been live in the app for weeks - and the point of the column is the offers
--    that come after it, not a retrospective announcement of the back catalogue.
UPDATE "Offer" SET "notifiedAt" = NOW() WHERE "notifiedAt" IS NULL;

-- 3. Load-bearing. If step 2 missed a row, the cost is a push to the entire customer base
--    for an offer they have already seen, which cannot be taken back. Guarded on the table
--    being non-empty so it holds on the empty shadow database `prisma migrate dev` replays
--    into (see 20260913000000_offer_renews_weekly).
DO $$
DECLARE
  offers      INTEGER;
  unannounced INTEGER;
BEGIN
  SELECT COUNT(*) INTO offers FROM "Offer";

  IF offers > 0 THEN
    SELECT COUNT(*) INTO unannounced FROM "Offer" WHERE "notifiedAt" IS NULL;

    IF unannounced <> 0 THEN
      RAISE EXCEPTION
        'offer announcement: % existing offer(s) left unannounced; the first sweep would push all of them',
        unannounced;
    END IF;
  END IF;
END $$;
