-- Monthly winner places + the reward they collect
--
-- Paste this over the body of the migration generated by:
--   npx prisma migrate diff --from-schema-datamodel <previous> \
--     --to-schema-datamodel prisma/schema.prisma --script
-- run from C:\Personal Projects\eversweet
--
-- Prisma's own generated SQL would do:
--   ALTER TABLE "LoyaltyWinner" DROP COLUMN "results", DROP COLUMN "rewardPickedUp",
--     ADD COLUMN "place" INTEGER NOT NULL DEFAULT 1;
-- Both columns have been unread by any of the three apps since the model was
-- written, but "no code reads it" is not "production has nothing in it", and a
-- dropped column does not come back. Step 1 asserts before step 3 destroys.
--
-- Prisma wraps each migration in a transaction, so a failed assertion here leaves
-- the database exactly as it was.

-- 1. Load-bearing assertion. Adding a CHECK validates every existing row, so this
--    fails and rolls the migration back if either column ever held anything. A
--    constraint rather than a DO block: it names itself in the error, and the
--    existing migrations assert with DDL for the same reason (see the SET NOT NULL
--    in offer_audience_and_redemption_rekey).
ALTER TABLE "LoyaltyWinner"
  ADD CONSTRAINT "loyaltywinner_dead_columns_empty"
  CHECK (coalesce(array_length("results", 1), 0) = 0 AND "rewardPickedUp" IS NULL);

-- 2. Place. DEFAULT 1 backfills every row written while only first place was
--    recorded, so the unique index in step 4 is already satisfied by existing data.
ALTER TABLE "LoyaltyWinner" ADD COLUMN "place" INTEGER NOT NULL DEFAULT 1;

-- 3. The dead columns, and the assertion that guarded them.
ALTER TABLE "LoyaltyWinner" DROP CONSTRAINT "loyaltywinner_dead_columns_empty";

ALTER TABLE "LoyaltyWinner" DROP COLUMN "results", DROP COLUMN "rewardPickedUp";

-- 4. One row per month becomes one row per place per month. The CREATE is itself an
--    assertion: had a month somehow carried two rows, it fails here — after the old
--    index is dropped, but inside the same transaction, so nothing is lost.
DROP INDEX "LoyaltyWinner_month_year_key";

CREATE UNIQUE INDEX "LoyaltyWinner_month_year_place_key"
  ON "LoyaltyWinner"("month", "year", "place");

-- 5. Cascade -> SetNull. Closing an account used to delete the record that they had
--    won; now it anonymises the row and leaves the shop's history intact.
ALTER TABLE "LoyaltyWinner" DROP CONSTRAINT "LoyaltyWinner_userId_fkey";

ALTER TABLE "LoyaltyWinner"
  ADD CONSTRAINT "LoyaltyWinner_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES "User"("id")
  ON DELETE SET NULL ON UPDATE CASCADE;

-- 6. The reward. Names match what Prisma generates, so a later `migrate diff`
--    reports an empty diff rather than proposing a rebuild.
CREATE TABLE "WinnerReward" (
    "id" TEXT NOT NULL,
    "winnerId" TEXT NOT NULL,
    "title" TEXT NOT NULL,
    "description" TEXT,
    "code" TEXT NOT NULL,
    "expiresAt" TIMESTAMP(3) NOT NULL,
    "assignedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "assignedByAdminId" TEXT,
    "redeemedAt" TIMESTAMP(3),
    "redeemedByAdminId" TEXT,

    CONSTRAINT "WinnerReward_pkey" PRIMARY KEY ("id")
);

CREATE UNIQUE INDEX "WinnerReward_winnerId_key" ON "WinnerReward"("winnerId");

CREATE UNIQUE INDEX "WinnerReward_code_key" ON "WinnerReward"("code");

CREATE INDEX "WinnerReward_redeemedAt_idx" ON "WinnerReward"("redeemedAt");

ALTER TABLE "WinnerReward"
  ADD CONSTRAINT "WinnerReward_winnerId_fkey"
  FOREIGN KEY ("winnerId") REFERENCES "LoyaltyWinner"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;