-- Offer audience + OfferRedemption re-key (membershipId -> userId)
--
-- Paste this over the body of the migration generated by:
--   npx prisma migrate dev --create-only --name offer_audience_and_redemption_rekey
-- run from C:\Personal Projects\eversweet
--
-- Prisma's own generated SQL would do:
--   ALTER TABLE "OfferRedemption" DROP COLUMN "membershipId",
--     ADD COLUMN "userId" TEXT NOT NULL;
-- which cannot succeed on a populated table and discards the association
-- anyway. The sequence below adds, backfills, asserts, then drops.
--
-- Prisma wraps each migration in a transaction, so a failure at step 3
-- leaves the database exactly as it was.

-- 1. Audience. NOT NULL DEFAULT 'MEMBERS' means every existing offer keeps
--    today's behaviour untouched until someone deliberately flips one.
CREATE TYPE "OfferAudience" AS ENUM ('MEMBERS', 'EVERYONE', 'NEW_USERS');

ALTER TABLE "Offer"
  ADD COLUMN "audience" "OfferAudience" NOT NULL DEFAULT 'MEMBERS';

-- 2. Add the new key nullable so existing rows survive the ALTER.
ALTER TABLE "OfferRedemption" ADD COLUMN "userId" TEXT;

-- 3. Backfill. Membership.userId is @unique and membershipId carries an FK,
--    so this maps every row exactly once: no NULLs, no duplicate pairs.
UPDATE "OfferRedemption" AS r
SET    "userId" = m."userId"
FROM   "Membership" AS m
WHERE  r."membershipId" = m."id"
  AND  r."userId" IS NULL;

-- 4. Load-bearing assertion. If step 3 missed a row this fails and rolls the
--    whole migration back rather than silently losing a redemption.
ALTER TABLE "OfferRedemption" ALTER COLUMN "userId" SET NOT NULL;

-- 5. Dropping the column takes its FK constraint and the old composite
--    unique index with it, so neither needs naming here.
ALTER TABLE "OfferRedemption" DROP COLUMN "membershipId";

-- 6. New key and FK, named to match what Prisma expects so that a later
--    `migrate diff` reports an empty diff rather than proposing a rebuild.
CREATE UNIQUE INDEX "OfferRedemption_offerId_userId_key"
  ON "OfferRedemption" ("offerId", "userId");

ALTER TABLE "OfferRedemption"
  ADD CONSTRAINT "OfferRedemption_userId_fkey"
  FOREIGN KEY ("userId") REFERENCES "User"("id")
  ON DELETE CASCADE ON UPDATE CASCADE;
