-- Weekly opening hours move from code into the database.
--
-- Paste this over the body of the migration generated by:
--   npx prisma migrate dev --create-only --name trading_hours
-- run from C:\Personal Projects\eversweet
--
-- Prisma's own generated SQL would create the table and nothing else. The hours were
-- hard-coded in five places - the website's checkout, the website's home page, the order
-- server, the customer app's fallback and a commented-out holiday copy - and the website's
-- checkout read them wrongly enough to offer pick-up times after closing. This migration
-- also adds the CHECK constraints Prisma cannot express, and seeds the hours every copy
-- agreed on, so reading the table changes nothing about when the shop is open.
--
-- Purely additive: nothing reads the table until the website and order server deploy, so
-- this runs before both.

-- 1. The table, exactly as Prisma would name it. Times are minutes past midnight on the
--    Pacific/Auckland wall clock; both null is a closed day.
CREATE TABLE "TradingHours" (
    "weekday" INTEGER NOT NULL,
    "opensAt" INTEGER,
    "closesAt" INTEGER,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "TradingHours_pkey" PRIMARY KEY ("weekday")
);

-- 2. One row per weekday, counted as JavaScript's getDay() counts them.
ALTER TABLE "TradingHours" ADD CONSTRAINT "TradingHours_weekday_in_week"
  CHECK ("weekday" BETWEEN 0 AND 6);

-- 3. A day is open or closed, never half of each. An opening time with no closing time
--    has no last pick-up, and every reader would have to guess what it meant.
ALTER TABLE "TradingHours" ADD CONSTRAINT "TradingHours_open_and_close_together"
  CHECK (("opensAt" IS NULL) = ("closesAt" IS NULL));

-- 4. Within the day. 1440 is midnight at the end of the day; the shop does not trade past
--    it, and nothing here models hours that cross midnight.
ALTER TABLE "TradingHours" ADD CONSTRAINT "TradingHours_within_the_day"
  CHECK ("opensAt" IS NULL OR ("opensAt" >= 0 AND "closesAt" <= 1440));

-- 5. The last pick-up is 10 minutes before closing, and must not fall before opening, or
--    the day would be open with nothing a customer could book.
ALTER TABLE "TradingHours" ADD CONSTRAINT "TradingHours_last_pick_up_after_opening"
  CHECK ("opensAt" IS NULL OR "closesAt" - 10 >= "opensAt");

-- 6. The hours that were hard-coded, unchanged.
INSERT INTO "TradingHours" ("weekday", "opensAt", "closesAt", "updatedAt") VALUES
  (0, 720, 1320, NOW()), -- Sunday    12:00 PM - 10:00 PM
  (1, 750, 1290, NOW()), -- Monday    12:30 PM -  9:30 PM
  (2, 750, 1290, NOW()), -- Tuesday   12:30 PM -  9:30 PM
  (3, 750, 1290, NOW()), -- Wednesday 12:30 PM -  9:30 PM
  (4, 750, 1290, NOW()), -- Thursday  12:30 PM -  9:30 PM
  (5, 720, 1320, NOW()), -- Friday    12:00 PM - 10:00 PM
  (6, 720, 1320, NOW()); -- Saturday  12:00 PM - 10:00 PM

-- 7. Assert every weekday has a row. Load-bearing: a missing weekday reads as closed to
--    both apps, which would quietly stop orders for that day. The table is created above,
--    so this holds on the empty shadow database `prisma migrate dev` replays into.
DO $$
DECLARE
  weekdays INTEGER;
BEGIN
  SELECT COUNT(DISTINCT "weekday") INTO weekdays FROM "TradingHours";

  IF weekdays <> 7 THEN
    RAISE EXCEPTION 'trading hours: expected a row for each of the 7 weekdays, found %', weekdays;
  END IF;
END $$;
